### PR TITLE
NoSQL Specification errata corrige.

### PR DESCRIPTION
**Pull request by DmitriGit**
The scope of this Pull Request is to improve the content of "NoSQL Specification".

### CODE REVIEW

**Comment by DmitriGit** [comment]
Hello,

in chapter 3 **"The main idea behind the API"** the phrase:
_"However, it requires more code to move it forward to the entity domain the portability is pretty down; therefore, the learning curve."_
seems not completed... 

Can give me a complete phrase so I commit and push it as part of this PR ?

Thank you!

**Comment by DmitriGit** [comment]
Hello,

at the end of the chapter 3 **"The main idea behind the API"** the phrase:

_"Thus, it will provide a straightforward specification, light maintenance; it will define the scope of each API; and it will work better in extensibility once the particular features matter to a NoSQL database.ut CDI events is how easy it creates and add new functionalities without changing the core code that is easy to use bean validation just to listen to an event."_

seems not completed... 

Can give me a complete phrase so I commit and push it as part of this PR ?

Thank you!

**Comment by otaviojava** [comment]
@DmitriGit 
Thank you.
We can remove the last paragraph without issue.

"Thus, it will provide a straightforward specification, light maintenance; it will define the scope of each API; and it will work better in extensibility once the particular features matter to a NoSQL database.ut"

Please, let me know what do you think.

**Comment by otaviojava** [comment]
@DmitriGit 
Could you solve this conflicting file?
spec/src/main/asciidoc/jakarta_nosql_spec.adoc

**Comment by DmitriGit** [comment]
> @DmitriGit
> Could you solve this conflicting file?
> spec/src/main/asciidoc/jakarta_nosql_spec.adoc

Yes, sure!

**Comment by DmitriGit** [comment]
At the middle of **4.2.1 "Make custom Writer and Reader"** the phrase:
_"With the MoneyValueWriter created and the Money type will save as String, then the next step is read information to Java application. As can be seen, a ValueReader implementation. "_

seems poorly worded phrase...

May be the phrase should be:
_"With the MoneyValueWriter created and the Money type **saved** as String, the next step is **to** read information to Java application. **That can be seen** in the ValueReader implementation. **The ValueReader** interface has two methods: "_
?

Let me know if my version is correctly express meaning.

Thank you!

**Comment by DmitriGit** [comment]
Hello,

at the start of 4.3 **"Element entity"** the phrase:
_"The Element entity is a small piece of a body, except a key-value structure type, once this structure is simple. E.g. The column family structure, the entity has columns, element entity with column has a tuple where the key is the name, and the value is the information as a Value implementation."_

seems poorly worded... In addition "E.g." seems out of context.

If I'm right, could you, please, give me a correct phrase?

Thank you!

**Comment by DmitriGit** [comment]
> @DmitriGit
> Thank you.
> We can remove the last paragraph without issue.
> 
> "Thus, it will provide a straightforward specification, light maintenance; it will define the scope of each API; and it will work better in extensibility once the particular features matter to a NoSQL database.ut"
> 
> Please, let me know what do you think.


Ok, removed.

**Comment by otaviojava** [comment]
@DmitriGit please, check the conflit

**Comment by DmitriGit** [comment]
Ok, sorry! I'll solve it definitely today. Sorry again. 

    On Tuesday, July 6, 2021, 10:09:04 AM GMT+2, Otávio Santana ***@***.***> wrote:  
 
 


@DmitriGit please, check the conflit

**Comment by DmitriGit** [comment]
Hello Team,

I found other many things to correct. Some examples:

1) _in "Search information on a column family":_
**ColumnQuery query = ColumnQuery query =** ColumnQueryBuilder.select().from("collection").where("age").lt(10).and("name").eq("Ada").orderBy("name").asc().limit(10).skip(2).build();

2) _in "4.5.3. BucketManager":_
BucketManager bucketManager= null;
 --- **I think it should be**: BucketManager bucketManager= //instance;

3) _in "5.3.4. Key-Value template":_
KeyValueTemplate template = null;
 --- **I think it should be**: KeyValueTemplate template= //instance;
 
4) _in "Create the Relationship Between Them (EdgeEntity)":_
Person poliana =...//instance;
Book shack =...//instance;
 --- **I think it should be**: Person poliana = //instance;
				      Book shack = //instance;

5) _in "5.3.6. Querying by text at Mapping API":_
KeyValueTemplate template = ...;
...
ColumnTemplate template = ...;
...
DocumentTemplate template = ...;
...
GraphTemplate template =...;
 --- **I think it should be**:  ClassName variable = //instance;


and many others similar to these or different.

Should I open a new PullRequest and:
1) we will discuss them one by one,
2) find a common standard.

Let me know.
Dmitri.

**Comment by otaviojava** [comment]
Hey that is nice!
Please move it forward with a PR.

**Pull request merged**
