### PR TITLE
Document CriteriaQuery API

### PR DESCRIPTION
**Pull request by amoscatelli**
As described in https://github.com/eclipse/jnosql/issues/263

I selected a first subset of JPA functionalities (the ones regarding the CriteriaQuery API).
This will allow a JPA style hierarchical and strongly typed query system based on predicates  on Entity Metadata

UpdateQuery and DeleteQuery will be released in other pull requests.

### CODE REVIEW

**Comment by amoscatelli** [comment]
This was autoclosed ... my fault ... I was fixing/moving the new API to the proper abstract (Document and not Column)

**Comment by amoscatelli** [comment]
@otaviojava sorry at first the new API was inserted in the wrong API (Column)
Now is in the correct one

**Comment by amoscatelli** [comment]
@otaviojava what do you think about this ?
How can I map the new functionalities to the old api ?
How should I proceed ?
Please help

**Comment by amoscatelli** [comment]
@otaviojava I cleaned the code as you asked.
No more extends Object and no more public modifier in interfaces.

I need the DocumentQuery builder to go further

**Comment by otaviojava** [comment]
Hey @amoscatelli, the code is on the master.
Please, let me know if you need more help on it.

**Comment by otaviojava** [comment]
Once we merged it on extension, I'll close this one.

**Pull request closed without merging**
