### PR TITLE
Fixes https://github.com/eclipse-ee4j/nosql/issues/11 and https://github.com/eclipse-ee4j/nosql/issues/12

### PR DESCRIPTION
**Pull request by keilw**

### CODE REVIEW

**Comment by genie-jnosql** [comment]
Can one of the admins verify this patch?

**Comment by otaviojava** [comment]
ok to test

**Comment by otaviojava** [comment]
test this please

**Comment by otaviojava** [comment]
* https://github.com/eclipse-ee4j/nosql/issues/11
* https://github.com/eclipse-ee4j/nosql/issues/12

**Comment by otaviojava** [comment]
Sucess: https://ci.eclipse.org/jnosql/job/jakarta-nosql/91/console

**Pull request merged**
