### PR TITLE
NoSQL Specification's content improvement and corrections.

### PR DESCRIPTION
**Pull request by DmitriGit**
Signed-off-by: Dmitri Cherkas <dmitricerkas@yahoo.com>

### CODE REVIEW

**Comment by otaviojava** [comment]
@DmitriGit why did you remove Spring Data as reference?

**Comment by DmitriGit** [comment]
Reference to "Spring Data" is mentioned twice (at the start and at the end of "6.1. Frameworks"):

"
**Spring Data
http://projects.spring.io/spring-data/**

Hibernate OGM
http://hibernate.org/ogm/

Eclipselink
http://www.eclipse.org/eclipselink/

Jdbc-json
https://github.com/jdbc-json/jdbc-cb

Simba
http://www.simba.com/drivers/

Apache Tinkerpop
http://tinkerpop.apache.org/

Apache Gora
http://gora.apache.org/about.html

**Spring Data
http://projects.spring.io/spring-data/**
"

**Comment by otaviojava** [comment]
Thank you

**Comment by DmitriGit** [comment]
I will change the format of table headers in "NoSQL Tutorial" (in "Jakarta EE Tutorial" table headers are in bold).
It's ok for you?

**Comment by otaviojava** [comment]
Yeap, that is ok to me @DmitriGit 
Please, go ahead

**Comment by DmitriGit** [comment]
Hi Team,

when I try to generate "Tutorial" locally with "mvn generate-resources" I've the following error:

_[ERROR] Failed to execute goal on project communication-query: Could not resolve dependencies for project jakarta.nosql.communication:communication-query:jar:1.0.0-SNAPSHOT: Could not find artifact jakarta.nosql.communication:communication-core:jar:1.0.0-SNAPSHOT_

Where am I doing wrong?

**Comment by otaviojava** [comment]
Hey, @DmitriGit what do you mean about "Tutorial"
Could you give me more detail?

**Comment by DmitriGit** [comment]
Sorry, sorry, no "Tutorial" :))) I meant "Specification".

**Comment by DmitriGit** [comment]
Hello, 

in chapter 3 **"The main idea behind the API"** the phrase: 
"_However, it requires more code to move it forward to the entity domain the portability is pretty down; therefore, the learning curve._"
seems not completed... If I'm right and you can give a complete phrase I'll commit it as part of this PR.

Thank you! :)

**Comment by otaviojava** [comment]
Please @DmitriGit send us a PR

**Comment by DmitriGit** [comment]
Hi Otavio, 

did I understand correctly to open a new PR for correct the phrase in chapter 3 "The main idea behind the API" ?
Then at this point we can use a new PR for all corrections that I'll find reading Specification, ok?

Thank you :)

**Comment by DmitriGit** [comment]
Also because at the end of the chapter 3 there is another probable error (the part highlighted in bold seems incomprehensible to me):
"
 Thus, it will provide a straightforward specification, light maintenance; it will define the scope of each API; and it will work better in extensibility once the particular features **_matter to a NoSQL database.ut CDI events is how easy_** it creates and add new functionalities without changing the core code that is easy to use bean validation just to listen to an event.
"

**Comment by DmitriGit** [comment]
:) Just for your information, NoSQL team: today finished debates about images format for Specifications (png vs. svg vs. PlantUML vs. other formats) and Kevin Sutter made a decision to use SVG format as official image format: 

"_@DmitriGit I just replied to the Platform mailing list that I feel that svg images are better than png and I don't want to lose out on your contribution. We can continue debating the pros and cons of the asciidoc images, but as the main maintainer of the Platform doc, I still prefer the svg format._"

So my work for NoSQL Specification to convert PNG to SVG was valid and I'm happy for it. :)

Thank you for opportunity to help you. :)

**Pull request merged**
