### PR TITLE
Update introduction.adoc

### PR DESCRIPTION
**Pull request by jasonwee**
read this documentation and found a minor spelling mistake.

### CODE REVIEW

**Comment by keilw** [comment]
@jasonwee Thanks but you seem to have no valid ECA in place, are you going to sign it soon? Otherwise we cannot accept this PR.

**Comment by jasonwee** [comment]
sorry, I just saw this and just recently signed.

**Comment by otaviojava** [comment]
No problem @jasonwee please signed and then create a PR again.

**Comment by jasonwee** [comment]
Just now I checked, the spelling already corrected, so no point of resubmission.

**Pull request closed without merging**
