### PR TITLE
Create a CHANGELOG file in repository

### PR DESCRIPTION
**Pull request by DanSilva41**
This simple PR adds a CHANGELOG file to the repository, based on existing release descriptions, in order to document the evolution of the specification.

Align if it is valid to include in the CHANGELOG:

- Issues references
- Author's username

### CODE REVIEW

**Comment by otaviojava** [comment]
@mpredli01 looks good for me, what do you think?

**Comment by mpredli01** [comment]
@otaviojava looks good to me, too!  Thanks, @DanSilva41 for putting this together.

**Comment by DanSilva41** [comment]
I appreciate the opportunity to collaborate with you, @otaviojava and @mpredli01!

By the way, are there any other repositories where we need to create a CHANGELOG file?

**Comment by otaviojava** [comment]
Yeap @DanSilva41 
https://github.com/eclipse/jnosql-communication-driver
https://github.com/eclipse/jnosql
https://github.com/eclipse/jnosql-mapping-extension

**Pull request merged**
