### PR TITLE
Reduce the Jakarta NoSQL only for High level API

### PR DESCRIPTION
**Pull request by otaviojava**
This PR reduces the Jakarta NoSQL scope for high-level abstraction. It will make it easier to have more implementation.

To Eclipse JNoSQL users, it won't impact anything once it goes to JNoSQL implementation.

## Changes

* Add Jakarta Data as API
* Remove communication as API
* Remove Repository to use Jakarta Data instead

:warning: for JNoSQL users, it will impact the package name. "jakarta.nosql"

Ref: https://github.com/eclipse-ee4j/nosql/issues/153

### CODE REVIEW

**Review by keilw — CHANGES_REQUESTED** [review]
Why was the DatabaseType removed?
Is there another way to tell which DB type you're using?

**Review by keilw — CHANGES_REQUESTED** [review]
Crippling and disabling much of the API without a proper replacement is not a good approach.
Why wasn't most of it parked e.g. in the https://github.com/JNOSQL orga instead of deleting it all?

Beside a significant API reduction must go via a Release Review by the Spec Committee first.

**Comment by otaviojava** [comment]
@keilw those are a good point, I'll move it to JNoQL and show the full show later next week.

**Comment by keilw** [comment]
@otaviojava Please wait till approached by @ivargrimstad or another mentor/Spec Committee Member.
Removing such big chunks of the API/SPI should not be done without a review.
And I saw, that except for a progress [review and ballot](https://www.eclipse.org/lists/jakarta.ee-spec/msg02795.html) last October, there have not been any release reviews for either Jakarta NoSQL or JNoSQL.

**Comment by otaviojava** [comment]
@keilw 

> Beside a significant API reduction must go via a Release Review by the Spec Committee first.

Yes that is the next step.

Ps: the release review happened through a milestone release, not a PR.
Reference: 
https://jakarta.ee/committees/specification/guide/

**Comment by keilw** [comment]
@otaviojava All of these were always done without a review, JNoSQL had the last release review on **May 15th, 2019**: https://projects.eclipse.org/projects/technology.jnosql
Anything that gets published to https://central.sonatype.dev/search?q=jakarta.nosql and not just a snapshot repo should have a review. 
> A progress review may be requested by the specification committee if no progress has been made in 12 months.

That means if you did not do one in one year it may be requested by the spec committee, but you're supposed to request a review from the project side, if you publish a milestone, especially with such a massive change. 
[Jakarta Config](https://projects.eclipse.org/projects/ee4j.jakartaconfig) just started with a totally clean slate, and maybe even that's something to explore for NoSQL instead of cutting half of it away ;-)

Either way, Config scheduled what seems like a progress review in May, so we should probably do the same here.

**Comment by ivargrimstad** [comment]
A couple of comments:
- I think the changes are within the scope of the spec project, so you are all good there
- A progress review about a year after the previous one is sufficient (unless you are close to a 1.0 release review then)


- JNoSQL is a separate open source project under the Technology PMC and does not need to be mixed into this discussion. Please refer to *that* PMC with anything regarding release reviews of such of that project as it is not a concern of the Jakarta EE Specification Committee or the EE4J PMC

**Comment by otaviojava** [comment]
Furthermore, @keilw, take look at here:

https://github.com/jakartaee/specifications/pull/587#issuecomment-1384220681

**Pull request merged**
