### PR TITLE
Redone NoSQL Tutorial images in svg format

### PR DESCRIPTION
**Pull request by DmitriGit**
Signed-off-by: N1-DCHERKAS\Dzmitry Cherkas <d.cherkas@be-tse.it>

### CODE REVIEW

**Comment by keilw** [comment]
@DmitriGit You don't seem to have a working ECA in place, so we are not allowed to merge it. Could you please sort that out, I'm sure the project mentor (and Jakarta EE Community Advocate) @ivargrimstad can help you where necessary.

**Comment by DmitriGit** [comment]
It's my error... I'he committed changes as ***@***.***" (my work account)... I committed 5 min ago as ***@***.***" (my Jakarta community's account).
Try it now please and sorry...
Dmitri.
    On Saturday, May 1, 2021, 05:03:38 PM GMT+2, Werner Keil ***@***.***> wrote:  
 
 


@DmitriGit You don't seem to have a working ECA in place, so we are not allowed to merge it. Could you please sort that out, I'm sure the project mentor (and Jakarta EE Community Advocate) @ivargrimstad can help you where necessary.

**Comment by otaviojava** [comment]
@DmitriGit did you update the file references?

**Comment by DmitriGit** [comment]
No... Where is file reference?

**Comment by otaviojava** [comment]
Hey @DmitriGit check the adoc files:

https://github.com/eclipse-ee4j/nosql/search?q=.png

**Comment by DmitriGit** [comment]
Ok, ok, I found references, thank you! :)
I'll commit all work (all images in a new format and reference files) aftertomorrow.

**Comment by DmitriGit** [comment]
Hello Team! :)
1) Images are converted (only "acid_vs_base.png" remain "png", but I'll find right template and convert it in the future),
2) file reference are updated.

Thank you,
Dmitri.

**Comment by DmitriGit** [comment]
If we'll need new images or something else for tutorial I'll do it with pleasure.

What the next? What do you want I do now, Team?
Starting today I analyse tutorial paragraph by paragraph. If you want to give some other activity apart from this I'll be happy.
Thank you again,Dmitri.

    On Friday, April 30, 2021, 11:20:21 PM GMT+2, eclipse-nosql-bot ***@***.***> wrote:  
 
 


Can one of the admins verify this patch?

**Comment by otaviojava** [comment]
Thank you @DmitriGit you can both review the spec and javadoc and check the JNoSQL website.

**Pull request merged**
